name: flutter_page_indicator
description: Page indicator for flutter, with multiple build-in layouts.
version: 1.0.0
homepage: https://github.com/jzoom/flutter_page_indicator

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
